### ISSUE TITLE
Error: Transaction: 0x12624ab93********** exited with an error (status 0) after consuming all gas

### ISSUE THREAD

**Issue by chahakshah111** [PatrickAlphaC/dungeons-and-dragons-nft#8]
Hey, @PatrickAlphaC i have cloned latest code of this repo.

So, i successfully deployed the D&D character: 0xA0813f82C27c18d2a0f9582Cb3a38919C43D9b29.

But, when i tired to execute funding script i got this error: 
![image](https://user-images.githubusercontent.com/81607081/123757719-e23cb980-d8db-11eb-9a77-29324f446d12.png)

Transaction: 0x12624ab938d0756cc33a9cbc9dc9168a5895cee29dd09157c7d96b4f874dd1a5.

Even with manual funding i'm getting error: 
![image](https://user-images.githubusercontent.com/81607081/123799806-352b6680-d906-11eb-932f-c7fe45501010.png)

And after that transaction just fails.

Can you please help me out with that.
Thank you.

**Comment by PatrickAlphaC** [comment]
Thanks for making this issue. Seems truffle isn't giving a very helpful answer. Do you have LINK in your testnet account?

**Comment by hieundx** [comment]
This happens because the contract you deployed didn't contain any LINK. Creating a new character consumes LINK to generate the random number, which is paid by the contract. So just go to MetaMask and send the contract some LINK.
Make sure the recipient is the contract at 0xA0813f82C27c18d2a0f9582Cb3a38919C43D9b29.
I tested this out myself and was able to create a random character: https://rinkeby.etherscan.io/tx/0x9f02c489c48e2b81700ab976bcbc321991779cdb397c150c03a210e544adade4

![sendlink](https://user-images.githubusercontent.com/32911537/124443541-f6832980-dda7-11eb-869d-199c13d76d21.PNG)

**Comment by PatrickAlphaC** [comment]
Closing for now, thanks @defiant99 !
